name: Scrape, Build - Manual

# on:
#  schedule:
#    - cron:  "0 11 * * *"
on: workflow_dispatch

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run - Scrape + Build GitHub Pages
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/erd_gov_lk/scrape.py
        python src/erd_gov_lk/build_gh_pages.py

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp /tmp/erd_gov_lk/data/* .
        echo "* $(date)" >> update.txt
        git add .
        git commit -m "Updated data $(date)"
        git push origin data

    - name: Checkout repo branch gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch gh-pages
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp /tmp/erd_gov_lk/gh-pages/* .
        echo "* $(date)" >> update.txt
        git add .
        git commit -m "Updated data $(date)"
        git push origin gh-pages
